### ISSUE TITLE
Feature Request: shortcut to activate/deactivate

### ISSUE THREAD

**Issue by courtneyr-dev** [artisticat1/nl-syntax-highlighting#8] opened 2023-04-03 15:42 UTC
I would love a simple shortcut to turn on or off my default settings for the plugin completely. As a user, I want to see the highlights when editing, but not when composing.

**Comment by danieltomasz** [comment] 2023-04-06 15:48
Would be great to have a command line to do it, indeed!

**Comment by danieltomasz** [comment] 2023-04-07 14:24
hi @courtneyr-dev  as a workaround you might use plugin `Plugin groups`, it is allowing to add separate commands to enable/disable specific plugin and then pin them to command palettes :)

**Comment by artisticat1** [comment] 2023-04-07 17:51
Closing as a duplicate of #5.

**Closed by artisticat1** 2023-04-07 17:51 UTC
